SERVER = irc.esper.net
BOT-NICKNAME = spaghettibot
BOT-IDENT = moms
BOT-REALNAME = arms
IDENTIFY-WITH-NICKSERV = true
NICKSERV-PASS = 
CHANNELS = #zack6849
VERIFY-BOT-ADMINS = true
BOT-ADMINS = zack6849 thereverend
EXEC-ADMINS = zack6849
ALLOW-FILE-TRANSFER = false
PUBLIC-IDENTIFIER = $
NOTICE-IDENTIFIER = |
PERMISSIONS-DENIED = Sorry you lack the necessary permissions to perform that action.
NOT-ADMIN = Sorry
DEBUG-MODE = true
ACCEPT-INVITIATIONS = true
LOGGED-CHANNELS = #zack6849 #thereverend403
